name: Release

on:
  push:
    branches:
      - v[0-9]+
      - "**beta"
    paths:
      - dist/index.js

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format-ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

  release:
    name: Release
    needs: lint-and-test
    runs-on: ubuntu-latest
    concurrency:
      group: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        run: npx --package @semantic-release/changelog@^5 --package @semantic-release/git@^9 --package semantic-release@^17 semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
